language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && ../build/noexcept_benchmark
