pool:
  vmImage: 'VS2017-Win2016'

steps:
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      cmake . -G "Visual Studio 15 2017 Win64"
      MSBuild.exe noexcept_benchmark.sln
      Release\noexcept_benchmark.exe
