jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
      mkdir build32
      cd build32
      cmake .. -G "Visual Studio 15 2017"
      MSBuild.exe ..\build32\noexcept_benchmark.sln  /p:Platform="Win32"
      ..\build32\Release\noexcept_benchmark.exe
      cd ..
      mkdir build32_no_throw
      cd build32_no_throw
      cmake -D NOEXCEPT_BENCHMARK_THROW_EXCEPTION:BOOL=OFF .. -G "Visual Studio 15 2017"
      MSBuild.exe ..\build32_no_throw\noexcept_benchmark.sln  /p:Platform="Win32"
      ..\build32_no_throw\Release\noexcept_benchmark.exe
      cd ..
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      mkdir build64
      cd build64
      cmake .. -G "Visual Studio 15 2017 Win64"
      MSBuild.exe ..\build64\noexcept_benchmark.sln
      ..\build64\Release\noexcept_benchmark.exe
      cd ..
      mkdir build64_no_throw
      cd build64_no_throw
      cmake -D NOEXCEPT_BENCHMARK_THROW_EXCEPTION:BOOL=OFF .. -G "Visual Studio 15 2017 Win64"
      MSBuild.exe ..\build64_no_throw\noexcept_benchmark.sln
      ..\build64_no_throw\Release\noexcept_benchmark.exe

- job: Ubuntu1604
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      mkdir build
      cd build
      cmake ..
      make && ../build/noexcept_benchmark
      cd ..
      mkdir build_no_throw
      cd build_no_throw
      cmake -D NOEXCEPT_BENCHMARK_THROW_EXCEPTION:BOOL=OFF ..
      make && ../build_no_throw/noexcept_benchmark

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      mkdir build
      cd build
      cmake ..
      make && ../build/noexcept_benchmark
      cd ..
      mkdir build_no_throw
      cd build_no_throw
      cmake -D NOEXCEPT_BENCHMARK_THROW_EXCEPTION:BOOL=OFF ..
      make && ../build_no_throw/noexcept_benchmark
